export const workshops = [
  {
    id: 1,
    title: "Authentic Thai Curry Masterclass",
    chef: "Chef Anong Srisuk",
    image: "/workshop/thai-curry.webp",
    description:
      "Dive into the world of Thai curries—from green to red to Massaman. Learn how to make curry paste from scratch, balance bold flavors, and cook fragrant, creamy dishes like a local.",
    dates: ["April 15, 2025", "May 20, 2025"],
    price: 110,
    duration: "3 hours",
    capacity: 12,
    level: "Beginner to Intermediate",
    includes: [
      "All ingredients",
      "Recipe booklet",
      "Thai iced tea",
      "Take-home curry paste",
    ],
  },
  {
    id: 2,
    title: "From Market to Wok: Thai Street Food Experience",
    chef: "Chef Somchai Rattanakosin",
    image: "/workshop/pad-thai.webp",
    description:
      "Begin your journey at a local Thai market selecting fresh herbs, spices, and vegetables. Then head to our kitchen to prepare iconic street food dishes like Pad Thai, satay, and mango sticky rice.",
    dates: ["April 22, 2025", "May 27, 2025"],
    price: 150,
    duration: "4.5 hours",
    capacity: 8,
    level: "All levels",
    includes: [
      "Market visit",
      "Transportation to kitchen",
      "Street food workshop",
      "Tasting session",
      "Mango sticky rice dessert",
    ],
  },
  {
    id: 3,
    title: "Thai Dumplings & Appetizers",
    chef: "Chef Mali Chanthaburi",
    image: "/workshop/thai-dumplings.webp",
    description:
      "Master the art of Thai appetizers. Learn to make kanom jeeb (Thai dumplings), crispy spring rolls, and spicy dipping sauces using traditional techniques and local ingredients.",
    dates: ["April 29, 2025", "May 13, 2025"],
    price: 90,
    duration: "3.5 hours",
    capacity: 10,
    level: "All levels",
    includes: [
      "All ingredients",
      "Dumpling mold",
      "Recipe cards",
      "Tasting of all dishes",
    ],
  },
  {
    id: 4,
    title: "Thai Mixology: Herbal Cocktails & Infusions",
    chef: "Mixologist Niran Boonyarat",
    image: "/workshop/thai-cocktail.webp",
    description:
      "Discover Thai-inspired cocktails using ingredients like lemongrass, kaffir lime, galangal, and Thai basil. Mix and shake your way through a vibrant and aromatic cocktail menu.",
    dates: ["May 6, 2025", "June 3, 2025"],
    price: 85,
    duration: "2.5 hours",
    capacity: 14,
    level: "All levels",
    includes: [
      "All ingredients",
      "Cocktail shaker set",
      "Signature drink recipes",
      "Herbal tasting flight",
    ],
  },
];
